// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

/**
 * Protobuf type {@code ds.VitalSignControlService.GetVitalSignsRequest}
 */
public  final class GetVitalSignsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ds.VitalSignControlService.GetVitalSignsRequest)
    GetVitalSignsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVitalSignsRequest.newBuilder() to construct.
  private GetVitalSignsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVitalSignsRequest() {
    patientID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetVitalSignsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            patientID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.VitalSignControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.VitalSignControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignControlService_GetVitalSignsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.VitalSignControlService.GetVitalSignsRequest.class, ds.VitalSignControlService.GetVitalSignsRequest.Builder.class);
  }

  public static final int PATIENTID_FIELD_NUMBER = 1;
  private int patientID_;
  /**
   * <code>int32 patientID = 1;</code>
   */
  public int getPatientID() {
    return patientID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (patientID_ != 0) {
      output.writeInt32(1, patientID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (patientID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, patientID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.VitalSignControlService.GetVitalSignsRequest)) {
      return super.equals(obj);
    }
    ds.VitalSignControlService.GetVitalSignsRequest other = (ds.VitalSignControlService.GetVitalSignsRequest) obj;

    boolean result = true;
    result = result && (getPatientID()
        == other.getPatientID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.VitalSignControlService.GetVitalSignsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.VitalSignControlService.GetVitalSignsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ds.VitalSignControlService.GetVitalSignsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ds.VitalSignControlService.GetVitalSignsRequest)
      ds.VitalSignControlService.GetVitalSignsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.VitalSignControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.VitalSignControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignControlService_GetVitalSignsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.VitalSignControlService.GetVitalSignsRequest.class, ds.VitalSignControlService.GetVitalSignsRequest.Builder.class);
    }

    // Construct using ds.VitalSignControlService.GetVitalSignsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      patientID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.VitalSignControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor;
    }

    @java.lang.Override
    public ds.VitalSignControlService.GetVitalSignsRequest getDefaultInstanceForType() {
      return ds.VitalSignControlService.GetVitalSignsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.VitalSignControlService.GetVitalSignsRequest build() {
      ds.VitalSignControlService.GetVitalSignsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.VitalSignControlService.GetVitalSignsRequest buildPartial() {
      ds.VitalSignControlService.GetVitalSignsRequest result = new ds.VitalSignControlService.GetVitalSignsRequest(this);
      result.patientID_ = patientID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.VitalSignControlService.GetVitalSignsRequest) {
        return mergeFrom((ds.VitalSignControlService.GetVitalSignsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.VitalSignControlService.GetVitalSignsRequest other) {
      if (other == ds.VitalSignControlService.GetVitalSignsRequest.getDefaultInstance()) return this;
      if (other.getPatientID() != 0) {
        setPatientID(other.getPatientID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.VitalSignControlService.GetVitalSignsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.VitalSignControlService.GetVitalSignsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int patientID_ ;
    /**
     * <code>int32 patientID = 1;</code>
     */
    public int getPatientID() {
      return patientID_;
    }
    /**
     * <code>int32 patientID = 1;</code>
     */
    public Builder setPatientID(int value) {
      
      patientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 patientID = 1;</code>
     */
    public Builder clearPatientID() {
      
      patientID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ds.VitalSignControlService.GetVitalSignsRequest)
  }

  // @@protoc_insertion_point(class_scope:ds.VitalSignControlService.GetVitalSignsRequest)
  private static final ds.VitalSignControlService.GetVitalSignsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.VitalSignControlService.GetVitalSignsRequest();
  }

  public static ds.VitalSignControlService.GetVitalSignsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVitalSignsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetVitalSignsRequest>() {
    @java.lang.Override
    public GetVitalSignsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetVitalSignsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetVitalSignsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVitalSignsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.VitalSignControlService.GetVitalSignsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

