// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

public interface GetVitalSignsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.VitalSignControlService.GetVitalSignsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientID = 1;</code>
   */
  int getPatientID();
}
