// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

public interface SetVitalSignsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.VitalSignControlService.SetVitalSignsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientID = 1;</code>
   */
  int getPatientID();

  /**
   * <code>.ds.VitalSignControlService.OperationalStatus result = 2;</code>
   */
  int getResultValue();
  /**
   * <code>.ds.VitalSignControlService.OperationalStatus result = 2;</code>
   */
  ds.VitalSignControlService.OperationalStatus getResult();

  /**
   * <code>string statusMessage = 3;</code>
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string statusMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
