// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

public interface VitalSignsMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.VitalSignControlService.VitalSignsMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientID = 1;</code>
   */
  int getPatientID();

  /**
   * <code>double time = 2;</code>
   */
  double getTime();

  /**
   * <code>int32 heartRateBPM = 3;</code>
   */
  int getHeartRateBPM();

  /**
   * <code>double bodyTemp = 4;</code>
   */
  double getBodyTemp();

  /**
   * <code>int32 Spo2 = 5;</code>
   */
  int getSpo2();
}
