// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

public final class VitalSignControlServiceImpl {
  private VitalSignControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_GetVitalSignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_GetVitalSignsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_GetVitalSignsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_SetVitalSignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_SetVitalSignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_SetVitalSignsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_SetVitalSignsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_VitalSignsMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_VitalSignsMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_VitalSignsMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_VitalSignsMonitorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_VitalSignsProblemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_VitalSignsProblemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignControlService_VitalSignsProblemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignControlService_VitalSignsProblemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027VitalSignsMonitor.proto\022\032ds.VitalSignC" +
      "ontrolService\")\n\024GetVitalSignsRequest\022\021\n" +
      "\tpatientID\030\001 \001(\005\"n\n\025GetVitalSignsRespons" +
      "e\022\021\n\tpatientID\030\001 \001(\005\022\014\n\004time\030\002 \001(\001\022\024\n\014he" +
      "artRateBPM\030\003 \001(\005\022\020\n\010bodyTemp\030\004 \001(\001\022\014\n\004Sp" +
      "o2\030\005 \001(\005\"m\n\024SetVitalSignsRequest\022\021\n\tpati" +
      "entID\030\001 \001(\005\022\014\n\004time\030\002 \001(\001\022\024\n\014heartRateBP" +
      "M\030\003 \001(\005\022\020\n\010bodyTemp\030\004 \001(\001\022\014\n\004Spo2\030\005 \001(\005\"" +
      "\200\001\n\025SetVitalSignsResponse\022\021\n\tpatientID\030\001" +
      " \001(\005\022=\n\006result\030\002 \001(\0162-.ds.VitalSignContr" +
      "olService.OperationalStatus\022\025\n\rstatusMes" +
      "sage\030\003 \001(\t\"q\n\030VitalSignsMonitorRequest\022\021" +
      "\n\tpatientID\030\001 \001(\005\022\014\n\004time\030\002 \001(\001\022\024\n\014heart" +
      "RateBPM\030\003 \001(\005\022\020\n\010bodyTemp\030\004 \001(\001\022\014\n\004Spo2\030" +
      "\005 \001(\005\"\204\001\n\031VitalSignsMonitorResponse\022\021\n\tp" +
      "atientID\030\001 \001(\005\022=\n\006result\030\002 \001(\0162-.ds.Vita" +
      "lSignControlService.OperationalStatus\022\025\n" +
      "\rstatusMessage\030\003 \001(\t\"I\n\030VitalSignsProble" +
      "mRequest\022\021\n\tpatientID\030\001 \001(\005\022\032\n\022problemDe" +
      "scription\030\002 \001(\t\"\204\001\n\031VitalSignsProblemRes" +
      "ponse\022\021\n\tpatientID\030\001 \001(\005\022=\n\006result\030\002 \001(\016" +
      "2-.ds.VitalSignControlService.Operationa" +
      "lStatus\022\025\n\rstatusMessage\030\003 \001(\t*G\n\021Operat" +
      "ionalStatus\022\r\n\tUndefined\020\000\022\013\n\007Success\020\001\022" +
      "\013\n\007Failure\020\002\022\t\n\005Error\020\0032\244\004\n\027VitalSignCon" +
      "trolService\022t\n\rGetVitalSigns\0220.ds.VitalS" +
      "ignControlService.GetVitalSignsRequest\0321" +
      ".ds.VitalSignControlService.GetVitalSign" +
      "sResponse\022v\n\rSetVitalSigns\0220.ds.VitalSig" +
      "nControlService.SetVitalSignsRequest\0321.d" +
      "s.VitalSignControlService.SetVitalSignsR" +
      "esponse(\001\022\213\001\n\030MonitorVitalSignsReading\0224" +
      ".ds.VitalSignControlService.VitalSignsMo" +
      "nitorRequest\0325.ds.VitalSignControlServic" +
      "e.VitalSignsMonitorResponse(\0010\001\022\214\001\n\035Aler" +
      "tStaffOfVitalSignsProblem\0224.ds.VitalSign" +
      "ControlService.VitalSignsProblemRequest\032" +
      "5.ds.VitalSignControlService.VitalSignsP" +
      "roblemResponseB;\n\032ds.VitalSignControlSer" +
      "viceB\033VitalSignControlServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_VitalSignControlService_GetVitalSignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_GetVitalSignsRequest_descriptor,
        new java.lang.String[] { "PatientID", });
    internal_static_ds_VitalSignControlService_GetVitalSignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_VitalSignControlService_GetVitalSignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_GetVitalSignsResponse_descriptor,
        new java.lang.String[] { "PatientID", "Time", "HeartRateBPM", "BodyTemp", "Spo2", });
    internal_static_ds_VitalSignControlService_SetVitalSignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ds_VitalSignControlService_SetVitalSignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_SetVitalSignsRequest_descriptor,
        new java.lang.String[] { "PatientID", "Time", "HeartRateBPM", "BodyTemp", "Spo2", });
    internal_static_ds_VitalSignControlService_SetVitalSignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ds_VitalSignControlService_SetVitalSignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_SetVitalSignsResponse_descriptor,
        new java.lang.String[] { "PatientID", "Result", "StatusMessage", });
    internal_static_ds_VitalSignControlService_VitalSignsMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ds_VitalSignControlService_VitalSignsMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_VitalSignsMonitorRequest_descriptor,
        new java.lang.String[] { "PatientID", "Time", "HeartRateBPM", "BodyTemp", "Spo2", });
    internal_static_ds_VitalSignControlService_VitalSignsMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ds_VitalSignControlService_VitalSignsMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_VitalSignsMonitorResponse_descriptor,
        new java.lang.String[] { "PatientID", "Result", "StatusMessage", });
    internal_static_ds_VitalSignControlService_VitalSignsProblemRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ds_VitalSignControlService_VitalSignsProblemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_VitalSignsProblemRequest_descriptor,
        new java.lang.String[] { "PatientID", "ProblemDescription", });
    internal_static_ds_VitalSignControlService_VitalSignsProblemResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ds_VitalSignControlService_VitalSignsProblemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignControlService_VitalSignsProblemResponse_descriptor,
        new java.lang.String[] { "PatientID", "Result", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
