// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsMonitor.proto

package ds.VitalSignControlService;

public interface VitalSignsProblemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.VitalSignControlService.VitalSignsProblemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientID = 1;</code>
   */
  int getPatientID();

  /**
   * <code>string problemDescription = 2;</code>
   */
  java.lang.String getProblemDescription();
  /**
   * <code>string problemDescription = 2;</code>
   */
  com.google.protobuf.ByteString
      getProblemDescriptionBytes();
}
