// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package ds.TestingService;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.TestingService.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dummyIn = 1;</code>
   */
  int getDummyIn();
}
