// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package ds.TestingService;

public final class TestingServiceImpl {
  private TestingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_TestingService_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_TestingService_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_TestingService_TestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_TestingService_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\021ds.TestingService\"\037\n\013TestR" +
      "equest\022\020\n\010dummyOut\030\001 \001(\005\"\037\n\014TestResponse" +
      "\022\017\n\007dummyIn\030\001 \001(\0052c\n\016TestingService\022Q\n\014t" +
      "estServices\022\036.ds.TestingService.TestRequ" +
      "est\032\037.ds.TestingService.TestResponse\"\000B)" +
      "\n\021ds.TestingServiceB\022TestingServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ds_TestingService_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_TestingService_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_TestingService_TestRequest_descriptor,
        new java.lang.String[] { "DummyOut", });
    internal_static_ds_TestingService_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_TestingService_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_TestingService_TestResponse_descriptor,
        new java.lang.String[] { "DummyIn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
