// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package ds.TestingService;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.TestingService.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dummyOut = 1;</code>
   */
  int getDummyOut();
}
