// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public interface GetClimateReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetClimateReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomID = 1;</code>
   */
  int getRoomID();

  /**
   * <code>float temperature = 2;</code>
   */
  float getTemperature();

  /**
   * <code>float humidity = 3;</code>
   */
  float getHumidity();
}
