// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

/**
 * Protobuf type {@code GetClimateReadingResponse}
 */
public  final class GetClimateReadingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetClimateReadingResponse)
    GetClimateReadingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetClimateReadingResponse.newBuilder() to construct.
  private GetClimateReadingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetClimateReadingResponse() {
    roomID_ = 0;
    temperature_ = 0F;
    humidity_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetClimateReadingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            roomID_ = input.readInt32();
            break;
          }
          case 21: {

            temperature_ = input.readFloat();
            break;
          }
          case 29: {

            humidity_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.SmartClimateControlService.SmartClimateControlServiceImpl.internal_static_GetClimateReadingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.SmartClimateControlService.SmartClimateControlServiceImpl.internal_static_GetClimateReadingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.SmartClimateControlService.GetClimateReadingResponse.class, ds.SmartClimateControlService.GetClimateReadingResponse.Builder.class);
  }

  public static final int ROOMID_FIELD_NUMBER = 1;
  private int roomID_;
  /**
   * <code>int32 roomID = 1;</code>
   */
  public int getRoomID() {
    return roomID_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private float temperature_;
  /**
   * <code>float temperature = 2;</code>
   */
  public float getTemperature() {
    return temperature_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 3;
  private float humidity_;
  /**
   * <code>float humidity = 3;</code>
   */
  public float getHumidity() {
    return humidity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roomID_ != 0) {
      output.writeInt32(1, roomID_);
    }
    if (temperature_ != 0F) {
      output.writeFloat(2, temperature_);
    }
    if (humidity_ != 0F) {
      output.writeFloat(3, humidity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roomID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, roomID_);
    }
    if (temperature_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, temperature_);
    }
    if (humidity_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, humidity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.SmartClimateControlService.GetClimateReadingResponse)) {
      return super.equals(obj);
    }
    ds.SmartClimateControlService.GetClimateReadingResponse other = (ds.SmartClimateControlService.GetClimateReadingResponse) obj;

    boolean result = true;
    result = result && (getRoomID()
        == other.getRoomID());
    result = result && (
        java.lang.Float.floatToIntBits(getTemperature())
        == java.lang.Float.floatToIntBits(
            other.getTemperature()));
    result = result && (
        java.lang.Float.floatToIntBits(getHumidity())
        == java.lang.Float.floatToIntBits(
            other.getHumidity()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomID();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHumidity());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SmartClimateControlService.GetClimateReadingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.SmartClimateControlService.GetClimateReadingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetClimateReadingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetClimateReadingResponse)
      ds.SmartClimateControlService.GetClimateReadingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.SmartClimateControlService.SmartClimateControlServiceImpl.internal_static_GetClimateReadingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.SmartClimateControlService.SmartClimateControlServiceImpl.internal_static_GetClimateReadingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.SmartClimateControlService.GetClimateReadingResponse.class, ds.SmartClimateControlService.GetClimateReadingResponse.Builder.class);
    }

    // Construct using ds.SmartClimateControlService.GetClimateReadingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      roomID_ = 0;

      temperature_ = 0F;

      humidity_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.SmartClimateControlService.SmartClimateControlServiceImpl.internal_static_GetClimateReadingResponse_descriptor;
    }

    @java.lang.Override
    public ds.SmartClimateControlService.GetClimateReadingResponse getDefaultInstanceForType() {
      return ds.SmartClimateControlService.GetClimateReadingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.SmartClimateControlService.GetClimateReadingResponse build() {
      ds.SmartClimateControlService.GetClimateReadingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.SmartClimateControlService.GetClimateReadingResponse buildPartial() {
      ds.SmartClimateControlService.GetClimateReadingResponse result = new ds.SmartClimateControlService.GetClimateReadingResponse(this);
      result.roomID_ = roomID_;
      result.temperature_ = temperature_;
      result.humidity_ = humidity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.SmartClimateControlService.GetClimateReadingResponse) {
        return mergeFrom((ds.SmartClimateControlService.GetClimateReadingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.SmartClimateControlService.GetClimateReadingResponse other) {
      if (other == ds.SmartClimateControlService.GetClimateReadingResponse.getDefaultInstance()) return this;
      if (other.getRoomID() != 0) {
        setRoomID(other.getRoomID());
      }
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getHumidity() != 0F) {
        setHumidity(other.getHumidity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.SmartClimateControlService.GetClimateReadingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.SmartClimateControlService.GetClimateReadingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int roomID_ ;
    /**
     * <code>int32 roomID = 1;</code>
     */
    public int getRoomID() {
      return roomID_;
    }
    /**
     * <code>int32 roomID = 1;</code>
     */
    public Builder setRoomID(int value) {
      
      roomID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomID = 1;</code>
     */
    public Builder clearRoomID() {
      
      roomID_ = 0;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 2;</code>
     */
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 2;</code>
     */
    public Builder setTemperature(float value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 2;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float humidity_ ;
    /**
     * <code>float humidity = 3;</code>
     */
    public float getHumidity() {
      return humidity_;
    }
    /**
     * <code>float humidity = 3;</code>
     */
    public Builder setHumidity(float value) {
      
      humidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float humidity = 3;</code>
     */
    public Builder clearHumidity() {
      
      humidity_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetClimateReadingResponse)
  }

  // @@protoc_insertion_point(class_scope:GetClimateReadingResponse)
  private static final ds.SmartClimateControlService.GetClimateReadingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.SmartClimateControlService.GetClimateReadingResponse();
  }

  public static ds.SmartClimateControlService.GetClimateReadingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetClimateReadingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetClimateReadingResponse>() {
    @java.lang.Override
    public GetClimateReadingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetClimateReadingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetClimateReadingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetClimateReadingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.SmartClimateControlService.GetClimateReadingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

