// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public interface GetClimateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetClimateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomID = 1;</code>
   */
  int getRoomID();
}
