// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public interface SetHumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetHumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float humidity = 1;</code>
   */
  float getHumidity();
}
