// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public interface SetHumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetHumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomID = 1;</code>
   */
  int getRoomID();

  /**
   * <code>float humidity = 2;</code>
   */
  float getHumidity();

  /**
   * <code>.OperationalStatus result = 3;</code>
   */
  int getResultValue();
  /**
   * <code>.OperationalStatus result = 3;</code>
   */
  ds.SmartClimateControlService.OperationalStatus getResult();

  /**
   * <code>string statusMessage = 4;</code>
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string statusMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
