// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public interface SetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   */
  float getTemperature();
}
