// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public final class SmartClimateControlServiceImpl {
  private SmartClimateControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClimateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClimateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClimateReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClimateReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetHumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetHumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetHumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetHumidityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SmartClimateControl.proto\"#\n\021GetClimat" +
      "eRequest\022\016\n\006roomID\030\001 \001(\005\"R\n\031GetClimateRe" +
      "adingResponse\022\016\n\006roomID\030\001 \001(\005\022\023\n\013tempera" +
      "ture\030\002 \001(\002\022\020\n\010humidity\030\003 \001(\002\",\n\025SetTempe" +
      "ratureRequest\022\023\n\013temperature\030\001 \001(\002\"x\n\026Se" +
      "tTemperatureResponse\022\016\n\006roomID\030\001 \001(\005\022\023\n\013" +
      "temperature\030\002 \001(\002\022\"\n\006result\030\003 \001(\0162\022.Oper" +
      "ationalStatus\022\025\n\rstatusMessage\030\004 \001(\t\"&\n\022" +
      "SetHumidityRequest\022\020\n\010humidity\030\001 \001(\002\"r\n\023" +
      "SetHumidityResponse\022\016\n\006roomID\030\001 \001(\005\022\020\n\010h" +
      "umidity\030\002 \001(\002\022\"\n\006result\030\003 \001(\0162\022.Operatio" +
      "nalStatus\022\025\n\rstatusMessage\030\004 \001(\t*G\n\021Oper" +
      "ationalStatus\022\r\n\tUndefined\020\000\022\013\n\007Success\020" +
      "\001\022\013\n\007Failure\020\002\022\t\n\005Error\020\0032\346\001\n\026SmartBedCo" +
      "ntrolService\022E\n\021GetClimateReading\022\022.GetC" +
      "limateRequest\032\032.GetClimateReadingRespons" +
      "e\"\000\022F\n\021SetTemperature_do\022\026.SetTemperatur" +
      "eRequest\032\027.SetTemperatureResponse\"\000\022=\n\016S" +
      "etHumidity_do\022\023.SetHumidityRequest\032\024.Set" +
      "HumidityResponse\"\000BA\n\035ds.SmartClimateCon" +
      "trolServiceB\036SmartClimateControlServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetClimateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetClimateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClimateRequest_descriptor,
        new java.lang.String[] { "RoomID", });
    internal_static_GetClimateReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetClimateReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClimateReadingResponse_descriptor,
        new java.lang.String[] { "RoomID", "Temperature", "Humidity", });
    internal_static_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "RoomID", "Temperature", "Result", "StatusMessage", });
    internal_static_SetHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SetHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetHumidityRequest_descriptor,
        new java.lang.String[] { "Humidity", });
    internal_static_SetHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SetHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetHumidityResponse_descriptor,
        new java.lang.String[] { "RoomID", "Humidity", "Result", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
