// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClimateControl.proto

package ds.SmartClimateControlService;

public final class SmartClimateControlServiceImpl {
  private SmartClimateControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClimateReadingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClimateReadingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClimateReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClimateReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetHumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetHumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetHumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetHumidityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SmartClimateControl.proto\"*\n\030GetClimat" +
      "eReadingRequest\022\016\n\006roomID\030\001 \001(\005\"R\n\031GetCl" +
      "imateReadingResponse\022\016\n\006roomID\030\001 \001(\005\022\023\n\013" +
      "temperature\030\002 \001(\002\022\020\n\010humidity\030\003 \001(\002\",\n\025S" +
      "etTemperatureRequest\022\023\n\013temperature\030\001 \001(" +
      "\002\"x\n\026SetTemperatureResponse\022\016\n\006roomID\030\001 " +
      "\001(\005\022\023\n\013temperature\030\002 \001(\002\022\"\n\006result\030\003 \001(\016" +
      "2\022.OperationalStatus\022\025\n\rstatusMessage\030\004 " +
      "\001(\t\"&\n\022SetHumidityRequest\022\020\n\010humidity\030\001 " +
      "\001(\002\"r\n\023SetHumidityResponse\022\016\n\006roomID\030\001 \001" +
      "(\005\022\020\n\010humidity\030\002 \001(\002\022\"\n\006result\030\003 \001(\0162\022.O" +
      "perationalStatus\022\025\n\rstatusMessage\030\004 \001(\t*" +
      "G\n\021OperationalStatus\022\r\n\tUndefined\020\000\022\013\n\007S" +
      "uccess\020\001\022\013\n\007Failure\020\002\022\t\n\005Error\020\0032\364\001\n\032Sma" +
      "rtClimateControlService\022O\n\024GetClimateRea" +
      "ding_do\022\031.GetClimateReadingRequest\032\032.Get" +
      "ClimateReadingResponse\"\000\022F\n\021SetTemperatu" +
      "re_do\022\026.SetTemperatureRequest\032\027.SetTempe" +
      "ratureResponse\"\000\022=\n\016SetHumidity_do\022\023.Set" +
      "HumidityRequest\032\024.SetHumidityResponse\"\000B" +
      "A\n\035ds.SmartClimateControlServiceB\036SmartC" +
      "limateControlServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetClimateReadingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetClimateReadingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClimateReadingRequest_descriptor,
        new java.lang.String[] { "RoomID", });
    internal_static_GetClimateReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetClimateReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClimateReadingResponse_descriptor,
        new java.lang.String[] { "RoomID", "Temperature", "Humidity", });
    internal_static_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "RoomID", "Temperature", "Result", "StatusMessage", });
    internal_static_SetHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SetHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetHumidityRequest_descriptor,
        new java.lang.String[] { "Humidity", });
    internal_static_SetHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SetHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetHumidityResponse_descriptor,
        new java.lang.String[] { "RoomID", "Humidity", "Result", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
