// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.SmartBedControlService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
