// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

public interface GetBedPositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.SmartBedControlService.GetBedPositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float bedHeadPosition = 1;</code>
   */
  float getBedHeadPosition();

  /**
   * <code>float bedFootPosition = 2;</code>
   */
  float getBedFootPosition();
}
