// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

/**
 * Protobuf enum {@code ds.SmartBedControlService.OperationalStatus}
 */
public enum OperationalStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Undefined = 0;</code>
   */
  Undefined(0),
  /**
   * <code>Success = 1;</code>
   */
  Success(1),
  /**
   * <code>Failure = 2;</code>
   */
  Failure(2),
  /**
   * <code>Error = 3;</code>
   */
  Error(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Undefined = 0;</code>
   */
  public static final int Undefined_VALUE = 0;
  /**
   * <code>Success = 1;</code>
   */
  public static final int Success_VALUE = 1;
  /**
   * <code>Failure = 2;</code>
   */
  public static final int Failure_VALUE = 2;
  /**
   * <code>Error = 3;</code>
   */
  public static final int Error_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperationalStatus valueOf(int value) {
    return forNumber(value);
  }

  public static OperationalStatus forNumber(int value) {
    switch (value) {
      case 0: return Undefined;
      case 1: return Success;
      case 2: return Failure;
      case 3: return Error;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperationalStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperationalStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationalStatus>() {
          public OperationalStatus findValueByNumber(int number) {
            return OperationalStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ds.SmartBedControlService.SmartBedControlServiceImpl.getDescriptor().getEnumTypes().get(0);
  }

  private static final OperationalStatus[] VALUES = values();

  public static OperationalStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperationalStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ds.SmartBedControlService.OperationalStatus)
}

