// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

/**
 * Protobuf type {@code ds.SmartBedControlService.SetBedHeadPositionRequest}
 */
public  final class SetBedHeadPositionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ds.SmartBedControlService.SetBedHeadPositionRequest)
    SetBedHeadPositionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetBedHeadPositionRequest.newBuilder() to construct.
  private SetBedHeadPositionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetBedHeadPositionRequest() {
    bedHeadPosition_ = 0F;
    result_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetBedHeadPositionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            bedHeadPosition_ = input.readFloat();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            result_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.SmartBedControlService.SmartBedControlServiceImpl.internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.SmartBedControlService.SmartBedControlServiceImpl.internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.SmartBedControlService.SetBedHeadPositionRequest.class, ds.SmartBedControlService.SetBedHeadPositionRequest.Builder.class);
  }

  public static final int BEDHEADPOSITION_FIELD_NUMBER = 1;
  private float bedHeadPosition_;
  /**
   * <code>float bedHeadPosition = 1;</code>
   */
  public float getBedHeadPosition() {
    return bedHeadPosition_;
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private int result_;
  /**
   * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
   */
  public int getResultValue() {
    return result_;
  }
  /**
   * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
   */
  public ds.SmartBedControlService.OperationalStatus getResult() {
    @SuppressWarnings("deprecation")
    ds.SmartBedControlService.OperationalStatus result = ds.SmartBedControlService.OperationalStatus.valueOf(result_);
    return result == null ? ds.SmartBedControlService.OperationalStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bedHeadPosition_ != 0F) {
      output.writeFloat(1, bedHeadPosition_);
    }
    if (result_ != ds.SmartBedControlService.OperationalStatus.Undefined.getNumber()) {
      output.writeEnum(2, result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bedHeadPosition_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, bedHeadPosition_);
    }
    if (result_ != ds.SmartBedControlService.OperationalStatus.Undefined.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.SmartBedControlService.SetBedHeadPositionRequest)) {
      return super.equals(obj);
    }
    ds.SmartBedControlService.SetBedHeadPositionRequest other = (ds.SmartBedControlService.SetBedHeadPositionRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getBedHeadPosition())
        == java.lang.Float.floatToIntBits(
            other.getBedHeadPosition()));
    result = result && result_ == other.result_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BEDHEADPOSITION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBedHeadPosition());
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + result_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.SmartBedControlService.SetBedHeadPositionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.SmartBedControlService.SetBedHeadPositionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ds.SmartBedControlService.SetBedHeadPositionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ds.SmartBedControlService.SetBedHeadPositionRequest)
      ds.SmartBedControlService.SetBedHeadPositionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.SmartBedControlService.SmartBedControlServiceImpl.internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.SmartBedControlService.SmartBedControlServiceImpl.internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.SmartBedControlService.SetBedHeadPositionRequest.class, ds.SmartBedControlService.SetBedHeadPositionRequest.Builder.class);
    }

    // Construct using ds.SmartBedControlService.SetBedHeadPositionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bedHeadPosition_ = 0F;

      result_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.SmartBedControlService.SmartBedControlServiceImpl.internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor;
    }

    @java.lang.Override
    public ds.SmartBedControlService.SetBedHeadPositionRequest getDefaultInstanceForType() {
      return ds.SmartBedControlService.SetBedHeadPositionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.SmartBedControlService.SetBedHeadPositionRequest build() {
      ds.SmartBedControlService.SetBedHeadPositionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.SmartBedControlService.SetBedHeadPositionRequest buildPartial() {
      ds.SmartBedControlService.SetBedHeadPositionRequest result = new ds.SmartBedControlService.SetBedHeadPositionRequest(this);
      result.bedHeadPosition_ = bedHeadPosition_;
      result.result_ = result_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.SmartBedControlService.SetBedHeadPositionRequest) {
        return mergeFrom((ds.SmartBedControlService.SetBedHeadPositionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.SmartBedControlService.SetBedHeadPositionRequest other) {
      if (other == ds.SmartBedControlService.SetBedHeadPositionRequest.getDefaultInstance()) return this;
      if (other.getBedHeadPosition() != 0F) {
        setBedHeadPosition(other.getBedHeadPosition());
      }
      if (other.result_ != 0) {
        setResultValue(other.getResultValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.SmartBedControlService.SetBedHeadPositionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.SmartBedControlService.SetBedHeadPositionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float bedHeadPosition_ ;
    /**
     * <code>float bedHeadPosition = 1;</code>
     */
    public float getBedHeadPosition() {
      return bedHeadPosition_;
    }
    /**
     * <code>float bedHeadPosition = 1;</code>
     */
    public Builder setBedHeadPosition(float value) {
      
      bedHeadPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float bedHeadPosition = 1;</code>
     */
    public Builder clearBedHeadPosition() {
      
      bedHeadPosition_ = 0F;
      onChanged();
      return this;
    }

    private int result_ = 0;
    /**
     * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
     */
    public Builder setResultValue(int value) {
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
     */
    public ds.SmartBedControlService.OperationalStatus getResult() {
      @SuppressWarnings("deprecation")
      ds.SmartBedControlService.OperationalStatus result = ds.SmartBedControlService.OperationalStatus.valueOf(result_);
      return result == null ? ds.SmartBedControlService.OperationalStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
     */
    public Builder setResult(ds.SmartBedControlService.OperationalStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
     */
    public Builder clearResult() {
      
      result_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ds.SmartBedControlService.SetBedHeadPositionRequest)
  }

  // @@protoc_insertion_point(class_scope:ds.SmartBedControlService.SetBedHeadPositionRequest)
  private static final ds.SmartBedControlService.SetBedHeadPositionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.SmartBedControlService.SetBedHeadPositionRequest();
  }

  public static ds.SmartBedControlService.SetBedHeadPositionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetBedHeadPositionRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetBedHeadPositionRequest>() {
    @java.lang.Override
    public SetBedHeadPositionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetBedHeadPositionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetBedHeadPositionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetBedHeadPositionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.SmartBedControlService.SetBedHeadPositionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

