// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

public interface SetBedHeadPositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.SmartBedControlService.SetBedHeadPositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float bedHeadPosition = 1;</code>
   */
  float getBedHeadPosition();

  /**
   * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
   */
  int getResultValue();
  /**
   * <code>.ds.SmartBedControlService.OperationalStatus result = 2;</code>
   */
  ds.SmartBedControlService.OperationalStatus getResult();

  /**
   * <code>string statusMessage = 3;</code>
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string statusMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
