// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

public interface SetBedFootPositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.SmartBedControlService.SetBedFootPositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float bedFootPosition = 1;</code>
   */
  float getBedFootPosition();
}
