// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartBedControl.proto

package ds.SmartBedControlService;

public final class SmartBedControlServiceImpl {
  private SmartBedControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_GetBedPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_GetBedPositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_ResetBedPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_ResetBedPositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_SetBedHeadPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_SetBedHeadPositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_SetBedFootPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_SetBedFootPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_SmartBedControlService_SetBedFootPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_SmartBedControlService_SetBedFootPositionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SmartBedControl.proto\022\031ds.SmartBedCont" +
      "rolService\"\007\n\005Empty\"J\n\026GetBedPositionRes" +
      "ponse\022\027\n\017bedHeadPosition\030\001 \001(\002\022\027\n\017bedFoo" +
      "tPosition\030\002 \001(\002\"\241\001\n\030ResetBedPositionResp" +
      "onse\022\027\n\017bedHeadPosition\030\001 \001(\002\022\027\n\017bedFoot" +
      "Position\030\002 \001(\002\022<\n\006result\030\003 \001(\0162,.ds.Smar" +
      "tBedControlService.OperationalStatus\022\025\n\r" +
      "statusMessage\030\004 \001(\t\"r\n\031SetBedHeadPositio" +
      "nRequest\022\027\n\017bedHeadPosition\030\001 \001(\002\022<\n\006res" +
      "ult\030\002 \001(\0162,.ds.SmartBedControlService.Op" +
      "erationalStatus\"\212\001\n\032SetBedHeadPositionRe" +
      "sponse\022\027\n\017bedHeadPosition\030\001 \001(\002\022<\n\006resul" +
      "t\030\002 \001(\0162,.ds.SmartBedControlService.Oper" +
      "ationalStatus\022\025\n\rstatusMessage\030\003 \001(\t\"4\n\031" +
      "SetBedFootPositionRequest\022\027\n\017bedFootPosi" +
      "tion\030\001 \001(\002\"\212\001\n\032SetBedFootPositionRespons" +
      "e\022\027\n\017bedFootPosition\030\001 \001(\002\022<\n\006result\030\002 \001" +
      "(\0162,.ds.SmartBedControlService.Operation" +
      "alStatus\022\025\n\rstatusMessage\030\003 \001(\t*G\n\021Opera" +
      "tionalStatus\022\r\n\tUndefined\020\000\022\013\n\007Success\020\001" +
      "\022\013\n\007Failure\020\002\022\t\n\005Error\020\0032\206\004\n\026SmartBedCon" +
      "trolService\022j\n\021GetBedPosition_do\022 .ds.Sm" +
      "artBedControlService.Empty\0321.ds.SmartBed" +
      "ControlService.GetBedPositionResponse\"\000\022" +
      "\206\001\n\025SetBedHeadPosition_do\0224.ds.SmartBedC" +
      "ontrolService.SetBedHeadPositionRequest\032" +
      "5.ds.SmartBedControlService.SetBedHeadPo" +
      "sitionResponse\"\000\022\206\001\n\025SetBedFootPosition_" +
      "do\0224.ds.SmartBedControlService.SetBedFoo" +
      "tPositionRequest\0325.ds.SmartBedControlSer" +
      "vice.SetBedFootPositionResponse\"\000\022n\n\023Res" +
      "etBedPosition_do\022 .ds.SmartBedControlSer" +
      "vice.Empty\0323.ds.SmartBedControlService.R" +
      "esetBedPositionResponse\"\000B9\n\031ds.SmartBed" +
      "ControlServiceB\032SmartBedControlServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ds_SmartBedControlService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_SmartBedControlService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_ds_SmartBedControlService_GetBedPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_SmartBedControlService_GetBedPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_GetBedPositionResponse_descriptor,
        new java.lang.String[] { "BedHeadPosition", "BedFootPosition", });
    internal_static_ds_SmartBedControlService_ResetBedPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ds_SmartBedControlService_ResetBedPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_ResetBedPositionResponse_descriptor,
        new java.lang.String[] { "BedHeadPosition", "BedFootPosition", "Result", "StatusMessage", });
    internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_SetBedHeadPositionRequest_descriptor,
        new java.lang.String[] { "BedHeadPosition", "Result", });
    internal_static_ds_SmartBedControlService_SetBedHeadPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ds_SmartBedControlService_SetBedHeadPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_SetBedHeadPositionResponse_descriptor,
        new java.lang.String[] { "BedHeadPosition", "Result", "StatusMessage", });
    internal_static_ds_SmartBedControlService_SetBedFootPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ds_SmartBedControlService_SetBedFootPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_SetBedFootPositionRequest_descriptor,
        new java.lang.String[] { "BedFootPosition", });
    internal_static_ds_SmartBedControlService_SetBedFootPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ds_SmartBedControlService_SetBedFootPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_SmartBedControlService_SetBedFootPositionResponse_descriptor,
        new java.lang.String[] { "BedFootPosition", "Result", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
