// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsControl.proto

package ds.VitalSignsControlService;

public interface GetVitalSignsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.VitalSignsControlService.GetVitalSignsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientID = 1;</code>
   */
  int getPatientID();
}
