// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsControl.proto

package ds.VitalSignsControlService;

/**
 * Protobuf type {@code ds.VitalSignsControlService.SetVitalSignsRequest}
 */
public  final class SetVitalSignsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ds.VitalSignsControlService.SetVitalSignsRequest)
    SetVitalSignsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetVitalSignsRequest.newBuilder() to construct.
  private SetVitalSignsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetVitalSignsRequest() {
    patientID_ = 0;
    heartRateBPM_ = 0;
    bodyTemp_ = 0D;
    spo2_ = 0;
    time_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetVitalSignsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            patientID_ = input.readInt32();
            break;
          }
          case 16: {

            heartRateBPM_ = input.readInt32();
            break;
          }
          case 25: {

            bodyTemp_ = input.readDouble();
            break;
          }
          case 32: {

            spo2_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            time_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.VitalSignsControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.VitalSignsControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.VitalSignsControlService.SetVitalSignsRequest.class, ds.VitalSignsControlService.SetVitalSignsRequest.Builder.class);
  }

  public static final int PATIENTID_FIELD_NUMBER = 1;
  private int patientID_;
  /**
   * <code>int32 patientID = 1;</code>
   */
  public int getPatientID() {
    return patientID_;
  }

  public static final int HEARTRATEBPM_FIELD_NUMBER = 2;
  private int heartRateBPM_;
  /**
   * <code>int32 heartRateBPM = 2;</code>
   */
  public int getHeartRateBPM() {
    return heartRateBPM_;
  }

  public static final int BODYTEMP_FIELD_NUMBER = 3;
  private double bodyTemp_;
  /**
   * <code>double bodyTemp = 3;</code>
   */
  public double getBodyTemp() {
    return bodyTemp_;
  }

  public static final int SPO2_FIELD_NUMBER = 4;
  private int spo2_;
  /**
   * <code>int32 Spo2 = 4;</code>
   */
  public int getSpo2() {
    return spo2_;
  }

  public static final int TIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object time_;
  /**
   * <code>string time = 5;</code>
   */
  public java.lang.String getTime() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      time_ = s;
      return s;
    }
  }
  /**
   * <code>string time = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTimeBytes() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      time_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (patientID_ != 0) {
      output.writeInt32(1, patientID_);
    }
    if (heartRateBPM_ != 0) {
      output.writeInt32(2, heartRateBPM_);
    }
    if (bodyTemp_ != 0D) {
      output.writeDouble(3, bodyTemp_);
    }
    if (spo2_ != 0) {
      output.writeInt32(4, spo2_);
    }
    if (!getTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, time_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (patientID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, patientID_);
    }
    if (heartRateBPM_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, heartRateBPM_);
    }
    if (bodyTemp_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, bodyTemp_);
    }
    if (spo2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, spo2_);
    }
    if (!getTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, time_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.VitalSignsControlService.SetVitalSignsRequest)) {
      return super.equals(obj);
    }
    ds.VitalSignsControlService.SetVitalSignsRequest other = (ds.VitalSignsControlService.SetVitalSignsRequest) obj;

    boolean result = true;
    result = result && (getPatientID()
        == other.getPatientID());
    result = result && (getHeartRateBPM()
        == other.getHeartRateBPM());
    result = result && (
        java.lang.Double.doubleToLongBits(getBodyTemp())
        == java.lang.Double.doubleToLongBits(
            other.getBodyTemp()));
    result = result && (getSpo2()
        == other.getSpo2());
    result = result && getTime()
        .equals(other.getTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientID();
    hash = (37 * hash) + HEARTRATEBPM_FIELD_NUMBER;
    hash = (53 * hash) + getHeartRateBPM();
    hash = (37 * hash) + BODYTEMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBodyTemp()));
    hash = (37 * hash) + SPO2_FIELD_NUMBER;
    hash = (53 * hash) + getSpo2();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.VitalSignsControlService.SetVitalSignsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.VitalSignsControlService.SetVitalSignsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ds.VitalSignsControlService.SetVitalSignsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ds.VitalSignsControlService.SetVitalSignsRequest)
      ds.VitalSignsControlService.SetVitalSignsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.VitalSignsControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.VitalSignsControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.VitalSignsControlService.SetVitalSignsRequest.class, ds.VitalSignsControlService.SetVitalSignsRequest.Builder.class);
    }

    // Construct using ds.VitalSignsControlService.SetVitalSignsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      patientID_ = 0;

      heartRateBPM_ = 0;

      bodyTemp_ = 0D;

      spo2_ = 0;

      time_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.VitalSignsControlService.VitalSignControlServiceImpl.internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor;
    }

    @java.lang.Override
    public ds.VitalSignsControlService.SetVitalSignsRequest getDefaultInstanceForType() {
      return ds.VitalSignsControlService.SetVitalSignsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.VitalSignsControlService.SetVitalSignsRequest build() {
      ds.VitalSignsControlService.SetVitalSignsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.VitalSignsControlService.SetVitalSignsRequest buildPartial() {
      ds.VitalSignsControlService.SetVitalSignsRequest result = new ds.VitalSignsControlService.SetVitalSignsRequest(this);
      result.patientID_ = patientID_;
      result.heartRateBPM_ = heartRateBPM_;
      result.bodyTemp_ = bodyTemp_;
      result.spo2_ = spo2_;
      result.time_ = time_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.VitalSignsControlService.SetVitalSignsRequest) {
        return mergeFrom((ds.VitalSignsControlService.SetVitalSignsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.VitalSignsControlService.SetVitalSignsRequest other) {
      if (other == ds.VitalSignsControlService.SetVitalSignsRequest.getDefaultInstance()) return this;
      if (other.getPatientID() != 0) {
        setPatientID(other.getPatientID());
      }
      if (other.getHeartRateBPM() != 0) {
        setHeartRateBPM(other.getHeartRateBPM());
      }
      if (other.getBodyTemp() != 0D) {
        setBodyTemp(other.getBodyTemp());
      }
      if (other.getSpo2() != 0) {
        setSpo2(other.getSpo2());
      }
      if (!other.getTime().isEmpty()) {
        time_ = other.time_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.VitalSignsControlService.SetVitalSignsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.VitalSignsControlService.SetVitalSignsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int patientID_ ;
    /**
     * <code>int32 patientID = 1;</code>
     */
    public int getPatientID() {
      return patientID_;
    }
    /**
     * <code>int32 patientID = 1;</code>
     */
    public Builder setPatientID(int value) {
      
      patientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 patientID = 1;</code>
     */
    public Builder clearPatientID() {
      
      patientID_ = 0;
      onChanged();
      return this;
    }

    private int heartRateBPM_ ;
    /**
     * <code>int32 heartRateBPM = 2;</code>
     */
    public int getHeartRateBPM() {
      return heartRateBPM_;
    }
    /**
     * <code>int32 heartRateBPM = 2;</code>
     */
    public Builder setHeartRateBPM(int value) {
      
      heartRateBPM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 heartRateBPM = 2;</code>
     */
    public Builder clearHeartRateBPM() {
      
      heartRateBPM_ = 0;
      onChanged();
      return this;
    }

    private double bodyTemp_ ;
    /**
     * <code>double bodyTemp = 3;</code>
     */
    public double getBodyTemp() {
      return bodyTemp_;
    }
    /**
     * <code>double bodyTemp = 3;</code>
     */
    public Builder setBodyTemp(double value) {
      
      bodyTemp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bodyTemp = 3;</code>
     */
    public Builder clearBodyTemp() {
      
      bodyTemp_ = 0D;
      onChanged();
      return this;
    }

    private int spo2_ ;
    /**
     * <code>int32 Spo2 = 4;</code>
     */
    public int getSpo2() {
      return spo2_;
    }
    /**
     * <code>int32 Spo2 = 4;</code>
     */
    public Builder setSpo2(int value) {
      
      spo2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Spo2 = 4;</code>
     */
    public Builder clearSpo2() {
      
      spo2_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object time_ = "";
    /**
     * <code>string time = 5;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string time = 5;</code>
     */
    public Builder setTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string time = 5;</code>
     */
    public Builder clearTime() {
      
      time_ = getDefaultInstance().getTime();
      onChanged();
      return this;
    }
    /**
     * <code>string time = 5;</code>
     */
    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      time_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ds.VitalSignsControlService.SetVitalSignsRequest)
  }

  // @@protoc_insertion_point(class_scope:ds.VitalSignsControlService.SetVitalSignsRequest)
  private static final ds.VitalSignsControlService.SetVitalSignsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.VitalSignsControlService.SetVitalSignsRequest();
  }

  public static ds.VitalSignsControlService.SetVitalSignsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetVitalSignsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetVitalSignsRequest>() {
    @java.lang.Override
    public SetVitalSignsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetVitalSignsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetVitalSignsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetVitalSignsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.VitalSignsControlService.SetVitalSignsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

