// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VitalSignsControl.proto

package ds.VitalSignsControlService;

public final class VitalSignControlServiceImpl {
  private VitalSignControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_GetVitalSignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_GetVitalSignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_GetVitalSignsLatestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_GetVitalSignsLatestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_GetVitalSignsHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_GetVitalSignsHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_SetVitalSignsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_SetVitalSignsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_VitalSignsMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_VitalSignsControlService_VitalSignsMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027VitalSignsControl.proto\022\033ds.VitalSigns" +
      "ControlService\")\n\024GetVitalSignsRequest\022\021" +
      "\n\tpatientID\030\001 \001(\005\"t\n\033GetVitalSignsLatest" +
      "Response\022\021\n\tpatientID\030\001 \001(\005\022\024\n\014heartRate" +
      "BPM\030\002 \001(\005\022\020\n\010bodyTemp\030\003 \001(\001\022\014\n\004Spo2\030\004 \001(" +
      "\005\022\014\n\004time\030\005 \001(\t\"u\n\034GetVitalSignsHistoryR" +
      "esponse\022\021\n\tpatientID\030\001 \001(\005\022\024\n\014heartRateB" +
      "PM\030\002 \001(\005\022\020\n\010bodyTemp\030\003 \001(\001\022\014\n\004Spo2\030\004 \001(\005" +
      "\022\014\n\004time\030\005 \001(\t\"m\n\024SetVitalSignsRequest\022\021" +
      "\n\tpatientID\030\001 \001(\005\022\024\n\014heartRateBPM\030\002 \001(\005\022" +
      "\020\n\010bodyTemp\030\003 \001(\001\022\014\n\004Spo2\030\004 \001(\005\022\014\n\004time\030" +
      "\005 \001(\t\"\201\001\n\025SetVitalSignsResponse\022\021\n\tpatie" +
      "ntID\030\001 \001(\005\022>\n\006result\030\002 \001(\0162..ds.VitalSig" +
      "nsControlService.OperationalStatus\022\025\n\rst" +
      "atusMessage\030\003 \001(\t\"q\n\030VitalSignsMonitorRe" +
      "quest\022\021\n\tpatientID\030\001 \001(\005\022\024\n\014heartRateBPM" +
      "\030\002 \001(\005\022\020\n\010bodyTemp\030\003 \001(\001\022\014\n\004Spo2\030\004 \001(\005\022\014" +
      "\n\004time\030\005 \001(\t\"\205\001\n\031VitalSignsMonitorRespon" +
      "se\022\021\n\tpatientID\030\001 \001(\005\022>\n\006result\030\002 \001(\0162.." +
      "ds.VitalSignsControlService.OperationalS" +
      "tatus\022\025\n\rstatusMessage\030\003 \001(\t*G\n\021Operatio" +
      "nalStatus\022\r\n\tUndefined\020\000\022\013\n\007Success\020\001\022\013\n" +
      "\007Failure\020\002\022\t\n\005Error\020\0032\271\004\n\030VitalSignsCont" +
      "rolService\022\205\001\n\026GetVitalSignsLatest_do\0221." +
      "ds.VitalSignsControlService.GetVitalSign" +
      "sRequest\0328.ds.VitalSignsControlService.G" +
      "etVitalSignsLatestResponse\022\211\001\n\027GetVitalS" +
      "ignsHistory_do\0221.ds.VitalSignsControlSer" +
      "vice.GetVitalSignsRequest\0329.ds.VitalSign" +
      "sControlService.GetVitalSignsHistoryResp" +
      "onse0\001\022y\n\020SetVitalSigns_do\0221.ds.VitalSig" +
      "nsControlService.SetVitalSignsRequest\0322." +
      "ds.VitalSignsControlService.SetVitalSign" +
      "sResponse\022\215\001\n\030MonitorVitalSignsReading\0225" +
      ".ds.VitalSignsControlService.VitalSignsM" +
      "onitorRequest\0326.ds.VitalSignsControlServ" +
      "ice.VitalSignsMonitorResponse(\0010\001B<\n\033ds." +
      "VitalSignsControlServiceB\033VitalSignContr" +
      "olServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ds_VitalSignsControlService_GetVitalSignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_VitalSignsControlService_GetVitalSignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_GetVitalSignsRequest_descriptor,
        new java.lang.String[] { "PatientID", });
    internal_static_ds_VitalSignsControlService_GetVitalSignsLatestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_VitalSignsControlService_GetVitalSignsLatestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_GetVitalSignsLatestResponse_descriptor,
        new java.lang.String[] { "PatientID", "HeartRateBPM", "BodyTemp", "Spo2", "Time", });
    internal_static_ds_VitalSignsControlService_GetVitalSignsHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ds_VitalSignsControlService_GetVitalSignsHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_GetVitalSignsHistoryResponse_descriptor,
        new java.lang.String[] { "PatientID", "HeartRateBPM", "BodyTemp", "Spo2", "Time", });
    internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_SetVitalSignsRequest_descriptor,
        new java.lang.String[] { "PatientID", "HeartRateBPM", "BodyTemp", "Spo2", "Time", });
    internal_static_ds_VitalSignsControlService_SetVitalSignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ds_VitalSignsControlService_SetVitalSignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_SetVitalSignsResponse_descriptor,
        new java.lang.String[] { "PatientID", "Result", "StatusMessage", });
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_VitalSignsMonitorRequest_descriptor,
        new java.lang.String[] { "PatientID", "HeartRateBPM", "BodyTemp", "Spo2", "Time", });
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ds_VitalSignsControlService_VitalSignsMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_VitalSignsControlService_VitalSignsMonitorResponse_descriptor,
        new java.lang.String[] { "PatientID", "Result", "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
